name: Build & Archive (Auto-Signing)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Install dependencies
        run: |
          brew install xcodegen # if you need it
          gem install fastlane  # optional if using fastlane lanes

      - name: Decode App Store Connect Key
        env:
          API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}
        run: |
          echo "$API_KEY_BASE64" | base64 --decode > AuthKey.p8

      - name: Build & Archive with Automatic Signing
        env:
          API_KEY_ID:       ${{ secrets.API_KEY_ID }}
          API_ISSUER_ID:    ${{ secrets.API_ISSUER_ID }}
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
        run: |
          xcodebuild \
            -project "CD starter project.xcodeproj" \
            -scheme "CD starter project" \
            -sdk iphoneos \
            -configuration Release \
            clean archive \
            -archivePath $PWD/build/CDStarterProject.xcarchive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            -allowProvisioningUpdates
