name: Test Comment Trigger

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  debug-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug comment event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Is pull request: ${{ github.event.issue.pull_request != null }}"
          echo "Pull request URL: ${{ github.event.issue.pull_request }}"
          
  test-comment:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '.test')
    runs-on: ubuntu-latest
    steps:
      - name: Respond to test comment
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d '{"body":"🤖 Test comment trigger is working! Comment was: `${{ github.event.comment.body }}`"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" 