name: Test Comment Trigger

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: read

jobs:
  test-comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '.test')
    runs-on: ubuntu-latest
    steps:
      - name: Respond to test comment
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d '{"body":"🤖 Test comment trigger is working! Comment was: ${{ github.event.comment.body }}"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" 